/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiStateWrapper: typeof import('./components/ApiStateWrapper.vue')['default']
    Calendar: typeof import('./components/Calendar.vue')['default']
    News: typeof import('./components/News.vue')['default']
    PatientsProfile: typeof import('./components/PatientsProfile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
